#!/usr/bin/env node
var buffers = [ ]
process.stdin
  .on('data', function(buffer) {
    buffers.push(buffer) })
  .on('end', function() {
    process.stdout.write(
      JSON.stringify(
        Array.from(
          new Set(
            Buffer.concat(buffers)
              .toString()
              .trim()
              .split('\n')
              .map(function(line) {
                return line.trim() })))
          .sort(),
        null,
        2) +
      '\n') })
